"""make description longer

Revision ID: 818648ce8dc8
Revises: cf8f394cc076
Create Date: 2024-11-04 21:46:03.591263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818648ce8dc8'
down_revision = 'cf8f394cc076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'description',
               existing_type=sa.VARCHAR(length=555),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=555),
               existing_nullable=True)
    op.alter_column('movies', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
